name: Tests & Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Set up Just
        uses: extractions/setup-just@v2

      - name: Install dependencies
        run: just install

      - name: Lint check
        run: just lint

      - name: Run tests
        run: just test
